export const DEFAULT_START_DATE = new Date('01/12/2019'.replace(
    /(\d+).(\d+).(\d+)/,
    '$3/$2/$1'))
export const DEFAULT_END_DATE = new Date('31/12/2020'.replace(
    /(\d+).(\d+).(\d+)/,
    '$3/$2/$1'))

export const COUNTRY_ASC = 'COUNTRY_ASC'
export const COUNTRY_DESC = 'COUNTRY_DESC'
export const CASES_ASC = 'CASES_ASC'
export const CASES_DESC = 'CASES_DESC'
export const DEATHS_ASC = 'DEATHS_ASC'
export const DEATHS_DESC = 'DEATHS_DESC'
export const ALL_CASES_ASC = 'ALL_CASES_ASC'
export const ALL_CASES_DESC = 'ALL_CASES_DESC'
export const ALL_DEATHS_ASC = 'ALL_DEATHS_ASC'
export const ALL_DEATHS_DESC = 'ALL_DEATHS_DESC'
export const CASES_PER_1000_PEOPLE_ASC = 'CASES_PER_1000_PEOPLE_ASC'
export const CASES_PER_1000_PEOPLE_DESC = 'CASES_PER_1000_PEOPLE_DESC'
export const DEATHS_PER_1000_PEOPLE_ASC = 'DEATHS_PER_1000_PEOPLE_ASC'
export const DEATHS_PER_1000_PEOPLE_DESC = 'DEATHS_PER_1000_PEOPLE_DESC'
export const AVERAGE_CASES_PER_DAY_ASC = 'AVERAGE_CASES_PER_DAY_ASC'
export const AVERAGE_CASES_PER_DAY_DESC = 'AVERAGE_CASES_PER_DAY_DESC'
export const AVERAGE_DEATHS_PER_DAY_ASC = 'AVERAGE_DEATHS_PER_DAY_ASC'
export const AVERAGE_DEATHS_PER_DAY_DESC = 'AVERAGE_DEATHS_PER_DAY_DESC'
export const MAX_CASES_PER_DAY_ASC = 'MAX_CASES_PER_DAY_ASC'
export const MAX_CASES_PER_DAY_DESC = 'MAX_CASES_PER_DAY_DESC'
export const MAX_DEATHS_PER_DAY_ASC = 'MAX_DEATHS_PER_DAY_ASC'
export const MAX_DEATHS_PER_DAY_DESC = 'MAX_DEATHS_PER_DAY_DESC'
export const ARROW_LEFT = '❮❮'
export const ARROW_RIGHT = '❯❯'
export const FILTER_BY_FIELD = 'FILTER_BY_FIELD'
export const COUNTRY = 'COUNTRY'
export const CASES = 'CASES'
export const DEATHS = 'DEATHS'
export const ALL_CASES = 'ALL_CASES'
export const ALL_DEATHS = 'ALL_DEATHS'
export const CASES_PER_1000 = 'CASES_PER_1000'
export const DEATHS_PER_1000 = 'DEATHS_PER_1000'
export const CASES_PER_DAY = 'CASES_PER_DAY'
export const DEATHS_PER_DAY = 'DEATHS_PER_DAY'
export const AVERAGE_CASES_PER_DAY = 'AVERAGE_CASES_PER_DAY'
export const AVERAGE_DEATHS_PER_DAY = 'AVERAGE_DEATHS_PER_DAY'
export const TABLE = 'TABLE'
export const GRAPHIC = 'GRAPHIC'
export const SET_PAGE_SIZE_SUBTITLE = 'Задайте размер странице'
export const ONLY_NUMBER_MISTAKE = 'Допускаются только числа'
export const NUMBER_RANGE_MISTAKE = 'Число должно быть не меньше 1 и не больше 20'
